package com.github.signed.sandboxes.spring.data.bg;


import com.github.signed.sandboxes.spring.data.H2Configuration;
import com.github.signed.sandboxes.spring.data.HibernateAutoGenerateDdlConfiguration;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = {H2Configuration.class, HibernateAutoGenerateDdlConfiguration.class})
public class JobsRepositoryTest {

    @Autowired
    private JobsRepository repository;

    @Test
    public void blub() throws Exception {
        Job job = new Job();
        job.state = JobState.Pending;
        job.type = JobType.ExecuteAction;
        job.referenceKey = 42L;
        repository.save(job);
    }
}