# https://spring.io/blog/2018/03/16/micrometer-spring-boot-2-s-new-application-metrics-collector
# http://www.baeldung.com/micrometer

GET http://localhost:8080/actuator/health

###
GET http://localhost:8080/actuator/info

###
GET http://localhost:8080/actuator/metrics

###
GET http://localhost:8080/actuator/trace

###