# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu-13.04-raring-64"

  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provision :puppet do |puppet|
    puppet.module_path = ["puppet/modules/","puppet/library/"]
    puppet.manifests_path = "puppet/manifests/"
    puppet.manifest_file  = "init.pp"
    puppet.options = "--verbose --debug"
  end
end
