FROM phusion/passenger-ruby22:0.9.15
MAINTAINER Thomas Heilbronner <thomas.heilbronner@gmail.com>

ENV HOME /root
# Use baseimage-docker's init process.
CMD ["/sbin/my_init"]

#setup dashing
USER app
RUN gem install dashing -v 1.3.4


# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*