package com.github.signed.xml.xstream.domain;

import org.joda.time.DateTime;

/*
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="acknowledgement.xsl"?>
<!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)-->
<AcknowledgementDocument DtdVersion="5" DtdRelease="0">
	<DocumentIdentification v="MyAcknowledgement"/>
	<DocumentDateTime v="2005-10-03T11:14:00Z"/>
	<SenderIdentification v="10XRECEIVER-OFD8" codingScheme="A01"/>
	<SenderRole v="A04"/>
	<ReceiverIdentification v="10XSENDER-OF-DO5" codingScheme="A01"/>
	<ReceiverRole v="A27"/>
	<ReceivingDocumentIdentification v="MyIdentification"/>
	<ReceivingDocumentVersion v="1"/>
	<Reason>
		<ReasonCode v="A05"/>
	</Reason>
</AcknowledgementDocument>
 */

public class AcknowledgementDocument {
	private DateTime DocumentDateTime;
	private Identification SenderIdentification = new Identification(new EicCode("10XRECEIVER-OFD8"));
	private Role SenderRole = Role.ReserveProvider;
	private Identification ReceiverIdentification = new Identification(new EicCode("10XSENDER-OF-DO5"));
	private Role ReceiverRole = Role.TransmissionSystemOperator; 
	
	public AcknowledgementDocument(DateTime documentDateTime) {
		DocumentDateTime = documentDateTime;
	}
	
	public DateTime dateTime() {
		return DocumentDateTime;
	}
}