GET https://secure.meetup.com/oauth2/authorize?client_id=6cl48m0hmuuqe44i5iqcrjrmo8&response_type=token&redirect_uri=https://localhost&scope=event_management

###
GET https://api.meetup.com/Softwerkskammer-Karlsruhe/events

###
HEAD https://api.meetup.com/Softwerkskammer-Karlsruhe/events

###
POST https://api.meetup.com/Softwerkskammer-Karlsruhe/events
Authorization: Bearer 123
Content-Type: application/x-www-form-urlencoded

name=draft-from-the-api&publish_status=draft&time=1533749400000&self_rsvp=true&venue_id=25894242&description=Catch+me+if+you+can%0AOn+multiple%0Alines%0Aover+and+over+again+<i>juhuu</i>

###
GET https://api.meetup.com/Softwerkskammer-Karlsruhe/events/253106023

###
