spring:
  security:
    oauth2:
      client:
        registration:
          github-client:
            client-id: abcd
            client-secret: password
            client-name: Client for user scope
            provider: my-oauth-provider
            scope: user
            redirect-uri-template: http://my-redirect-uri.com
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: http://my-auth-server/oauth/authorize
            token-uri: http://my-auth-server/oauth/token
            user-info-uri: http://my-auth-server/userinfo
            jwk-set-uri: http://my-auth-server/token_keys
            user-name-attribute: name

security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
