### echo call
POST http://localhost:3000/api/challenge
Content-Type: application/json

{
  "challenge": "45 + 5"
}

### Identity
POST http://localhost:3000/identity
Content-Type: application/json

{
  "challenge": "45 + 3"
}
