# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::configure("2") do |config|

  config.vm.box = "precise32-latest"
  #config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  config.ssh.username

  config.vm.synced_folder "../augeas/", "/augeas"


  config.vm.provider "virtualbox" do |virtualbox|
    #put your box specific stuff here
  end

  config.vm.provision :puppet do |puppet|
    puppet.module_path = ["puppet/modules/","puppet/library/"]
    puppet.manifests_path = "puppet/manifests/"
    puppet.manifest_file  = "init.pp"
    #puppet.options = "--verbose --debug"
  end
end
