info:
  project:
    version: @project.version@
  build:
    number: 42
    time: @git.build.time@
    host: @git.build.host@
    branch: @git.branch@
    commit:
      id: @git.commit.id@
      username: @git.commit.user.name@
      message: @git.commit.message.short@
